### ISSUE TITLE
Getting "Too many HTTP redirects" when attempting to file radars

### ISSUE THREAD

**Issue by ZevEisenberg** [amyworrall/QuickRadar#89]
I'm assuming they made changes at WWDC 2016? Reproduced on two machines with two different developer accounts. It happens on the "Signing in to RadarWeb" step.

<img width="894" alt="screen shot 2016-06-14 at 7 28 32 am" src="https://cloud.githubusercontent.com/assets/464574/16046531/a0283a78-3201-11e6-9f8d-691bccdb7772.png">

**Comment by orta** [comment]
I don't have the time to do a full PR, but running this in debug mode brings up this: 

```
2016-06-15 17:56:03.107429 QuickRadar[10053:763605] Found no element //img[@id='alert_icon']/@src
2016-06-15 17:56:06.863055 QuickRadar[10053:761345] Failure by QRRadarSubmissionServiceIdentifier
```

Likely this is the change

**Comment by keith** [comment]
It looks like at this state the entire `xmlDocument` only contains this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Apple</title><meta http-equiv="REFRESH" content="0;URL=http://www.apple.com/filenotfound" /></head><body bgcolor="#FFFFFF"></body></html>```

**Comment by abbeycode** [comment]
I'm getting this also.

**Comment by orta** [comment]
Digging in a bit further, now I'm back in NYC, this is the new re-direction path ( had to write a quick app ) - will see about wrapping this up and making a PR

```
2016-06-19 13:52:07.318 LinkChecker[6856:956926] action: {
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 5;
    WebActionOriginalURLKey = "https://idmsa.apple.com/IDMSWebAuth/login.html?appIdKey=77e2a60d4bdfa6b7311c854a56505800be3c24e3a27a670098ff61b69fc5214b&sslEnabled=true&rv=3";
}
2016-06-19 13:52:32.895 LinkChecker[6856:956926] action: {
    WebActionButtonKey = 0;
    WebActionElementKey =     {
       ...
    };
    WebActionFormKey = "<DOMHTMLFormElement [FORM]: 0x10cbe3a80 ''>";
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 1;
    WebActionOriginalURLKey = "https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=6A6F10E58CA810EC1D701A4C466351A1";
}
2016-06-19 13:52:33.444 LinkChecker[6856:956926] action: {
    WebActionButtonKey = 0;
    WebActionElementKey =     {
      ...
    };
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 1;
    WebActionOriginalURLKey = "https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=6A6F10E58CA810EC1D701A4C466351A1";
}
2016-06-19 13:52:33.883 LinkChecker[6856:956926] action: {
    WebActionButtonKey = 0;
    WebActionElementKey =     {
    ...
    };
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 1;
    WebActionOriginalURLKey = "https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=6A6F10E58CA810EC1D701A4C466351A1";
}
2016-06-19 13:52:34.278 LinkChecker[6856:956926] action: {
    WebActionButtonKey = 0;
    WebActionElementKey =     {
    ...
    };
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 1;
    WebActionOriginalURLKey = "https://idmsa.apple.com/IDMSWebAuth/authenticate;jsessionid=6A6F10E58CA810EC1D701A4C466351A1";
}
2016-06-19 13:52:35.573 LinkChecker[6856:956926] action: {
    WebActionModifierFlagsKey = 0;
    WebActionNavigationTypeKey = 5;
    WebActionOriginalURLKey = "about:blank";
}

```

**Comment by orta** [comment]
I threw an hour or two at this before calling it for the evening, looks like in late may authentication changed:

![screen shot 2016-06-20 at 3 28 33 pm](https://cloud.githubusercontent.com/assets/49038/16207547/acdc18c6-36fb-11e6-8d50-593fd3c2719f.png)

I couldn't find the CRSF token in the new urls

**Comment by steipete** [comment]
Thanks for fixing this! Gotta love open source!

Also note this comment that hints on a undocumented radar JavaScript API that might be less fragile:
http://www.openradar.me/26886178

**Comment by matej** [comment]
After some digging around I managed to get the app running again. By deleting some code. 

Specifically I removed the code that manually sets the Host field:
 - https://github.com/amyworrall/QuickRadar/blob/e63a16d1feb6c980290b2ac96fb0b1305f9142e9/QuickRadar/QRURLConnection.m#L131
 - https://github.com/amyworrall/QuickRadar/blob/e63a16d1feb6c980290b2ac96fb0b1305f9142e9/QuickRadar/QRURLConnection.m#L141

Doing that messes up the redirect we get after sending our authentication data, directing us to `https://idmsa.apple.com/logon` instead of `https://bugreport.apple.com/logon`. 

I noticed this by comparing the reqests Safari and QuickRadar make during login. 

Safari / request:
```
GET / HTTP/1.1
Host: bugreport.apple.com
DNT: 1
Cookie: <redacted>
Connection: keep-alive
Proxy-Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
Accept-Language: en-us
Referer: https://idmsa.apple.com/IDMSWebAuth/login.html?appIdKey=77e2a60d4bdfa6b7311c854a56505800be3c24e3a27a670098ff61b69fc5214b&sslEnabled=true&rv=3
Accept-Encoding: gzip, deflate
```
Safari / respnse:
```
HTTP/1.1 302 Moved Temporarily
Date: Thu, 23 Jun 2016 12:24:14 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-API-Version: 1.8
Cache-Control: no-cache, no-store, must-revalidate, private
Pragma: no-cache
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains
Location: https://bugreport.apple.com/logon
Content-Language: en-US
Content-Length: 0
Keep-Alive: timeout=15, max=4998
Connection: Keep-Alive
Content-Type: text/html;charset=ISO-8859-1
```


QuickRadar / request:
```
GET / HTTP/1.1
Host: idmsa.apple.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Accept-Language: en-us
Proxy-Connection: keep-alive
Cookie: <redacted>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1
Referer: https://idmsa.apple.com/IDMSWebAuth/login.html?appIdKey=77e2a60d4bdfa6b7311c854a56505800be3c24e3a27a670098ff61b69fc5214b&sslEnabled=true&rv=3
Accept-Encoding: gzip, deflate
```
QuickRadar / response:
```
HTTP/1.1 302 Moved Temporarily
Date: Thu, 23 Jun 2016 12:15:43 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-API-Version: 1.8
Cache-Control: no-cache, no-store, must-revalidate, private
Pragma: no-cache
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains
Set-Cookie: JSESSIONID=elPy-v0NpECJPBgkApiTfhci.nwk-radarp-lapp57; Path=/; Secure; HttpOnly
Location: https://idmsa.apple.com/logon
Content-Language: en-US
Content-Length: 0
Keep-Alive: timeout=15, max=5000
Connection: Keep-Alive
Content-Type: text/html;charset=ISO-8859-1
```

Notice the difference for `Host` and `Location`. 

I don't know the background here - why this has been done in the first place. But simply deleting those lines seems to do the trick for me. I can open up a PR for that, unless someone has a better idea.

**Comment by amyworrall** [comment]
If it works, I say go for it! 

Most of the stuff QuickRadar sends just came from me observing a lot of sessions in Charles, and trying adding things until it worked. So this is exactly in keeping with the way the app has been built :)

Amy

**Comment by abbeycode** [comment]
Is there any ETA on when a new build will be released?

**Comment by chockenberry** [comment]
I'm building from master using #90 and still seeing these errors.

One thing I have noticed is that the errors occur after I submit my first Radar (e.g. first one works fine, but subsequent ones do not.) Maybe there's something getting cached in the URL connection?

**Comment by ZevEisenberg** [comment]
@chockenberry confirmed: success the first time, "too many HTTP redirects" the second time.

**Comment by chockenberry** [comment]
@amyworrall Sounds like this issue should be reopened. I'm wondering if @steipete and @matej are seeing the same "works the first time, not the second" behavior.

**Comment by amyworrall** [comment]
I'm so sorry that I haven't had any time to look at this yet. I'm a bit swamped at the moment (plus my country is imploding politically, which is distracting). Thanks to everyone who is helping!

**Comment by steipete** [comment]
True. Noticed this as well today. This works once but then it's trouble again... probably won't be as easy to fix than just deleting a line. But it went from not working at all to at least somewhat working :)

**Comment by matej** [comment]
Looks like that's their way to rate limit you guys. ;)

The requests do differ between the first and second attempt. 

One thing I noticed is that the authenticate action on the login page no longer has the session ID the second time around. 

![screen shot 2016-07-01 at 08 00 23](https://cloud.githubusercontent.com/assets/91322/16514312/5b19e522-3f6b-11e6-8457-9e93309360b4.png)

This leads to a different authenticate URL being invoked and things go south from there on. 

First:
![screen shot 2016-07-01 at 07 59 14](https://cloud.githubusercontent.com/assets/91322/16514364/a5d2e03c-3f6b-11e6-9cb9-f00fe23575d9.png)

Second:
![screen shot 2016-07-01 at 07 59 32](https://cloud.githubusercontent.com/assets/91322/16514365/ad2f5e32-3f6b-11e6-9288-aab320b54181.png)

There is probably no need to even login at this point (the session could be reused). But since that would require even more and special casing, I just decided to purge cookies before we start. That should make every request equal to the first one. Seems to work. 

Just deleting the "myacinfo" cookie appears to be enough, so this could be limited a bit, if anyone has any good arguments on why we should keep the remaining ones.
